"""Apply the fully accepted 1% weak-scaling evidence to the final manuscript."""
from pathlib import Path
import json,re
ROOT=Path(__file__).resolve().parents[1]

def replace_section(text,start,end,body):
    assert start in text and end in text
    a=text.index(start);b=text.index(end,a)
    return text[:a]+body.rstrip()+'\n\n'+text[b:]

def main():
    evidence=json.loads((ROOT/'data/capacity/weak-evidence.json').read_text())
    rows=evidence['rows'];assert [r['hosts'] for r in rows]==[3,6,12,24,30]
    assert rows[-1]['neurons']==860_000_000 and all(r['passed'] and r['cleanup_passed'] for r in rows)
    first,last=rows[0],rows[-1]
    final_reserve=last.get('host_memory_reserve_gib',64)
    assert final_reserve in [48,64]
    reserve_text=('a 64 GiB host-memory reserve' if final_reserve==64 else
                  'a 64 GiB host-memory reserve at 3–24 hosts and a 48 GiB reserve at 30 hosts')
    path=ROOT/'MANUSCRIPT.md';text=path.read_text()
    old='A separate connected synthetic workload reached 128 million neurons and 128 billion recurrent connections for 100 ms on 30 hosts.'
    new='A five-point synthetic weak-scaling study reached 860 million neurons and 860 billion recurrent connections for 100 ms on 30 hosts and 240 physical worker cores, increasing from 86 million neurons on three hosts.'
    assert old in text;text=text.replace(old,new)
    text=text.replace('Appendix A (Table 6)', 'Appendix A (Table 7)')
    old_cohort='| Connected synthetic MPI capacity | 86 million / 86 billion; 128 million / 128 billion | 100 ms | 30 hosts, 30 populated ranks; one observation per size | Launch through initialization, simulation and complete output |'
    new_cohort='| Connected synthetic MPI weak scaling | 86–860 million / 86–860 billion | 100 ms | 3/6/12/24/30 hosts, eight physical worker cores per host; one observation per size | Preparation and launch through complete output, reported separately |'
    assert old_cohort in text;text=text.replace(old_cohort,new_cohort)
    methods='''### 4.8 Connected synthetic weak-scaling protocol

The additional study increases network size with host count across 3, 6, 12, 24 and 30 physical EPYC 9454 hosts, using eight populated single-threaded MPI ranks on eight distinct physical cores per host. Each repeated three-host block adds 86 million neurons, arranged in 19 excitatory populations containing 80% of neurons and five inhibitory populations containing 20%. One rank owns each complete population. The three hosts in a block own six excitatory/two inhibitory, six/two, and seven/one populations, respectively. Per-rank neuron and incoming-edge workloads therefore remain approximately constant. The five configurations have 24, 48, 96, 192 and 240 populations and 86, 172, 344, 688 and 860 million neurons.

Every directed population pair has fixed-total uniform random connections with replacement, permitting autapses and multapses. Counts are integer floors of source-count times target-count times 1,000 divided by total neuron count; largest-remainder allocation preserves exactly 1,000N edges. This fixes expected mean indegree rather than the indegree of every neuron. Model seed is 20261007 and projection seeds are 2026100700 + source×P + target in numeric population-creation order, where P is population count. The graph realization changes with size. Whole-population target-owner-local construction preserves source-major connection identities and avoids per-projection count/routing construction collectives.

Euler LIF dynamics use reference-f64, dt = 0.1 ms, membrane and current time constants of 20 and 5 ms, drive 1.05, threshold 1, reset 0 and a 2 ms refractory interval. Excitatory weights are uniform in [0.0027, 0.0033], inhibitory weights in [-0.0132, -0.0108]. Clipped-normal delays have mean 1.5 ms, standard deviation 0.25 ms and bounds 0.1–3 ms. Initial voltage cycles through 1,000 deterministic values. All spikes and voltage/current traces from two neurons per population are retained for 100 ms.

All five configurations use one isolated engine snapshot, with an opt-in neuron ceiling of 860 million and an unchanged default ceiling of one million. Initial-value and IR-byte budgets are four billion values and 64 GiB. Worker cgroup limits are 665 GiB for the first three layouts and 655/660 GiB for the final two (six-excitatory/two-inhibitory versus seven-excitatory/one-inhibitory host layouts), with 768 GiB on the coordinator host; swap is disabled. Each launch requires a fresh availability check with a 64 GiB host-memory reserve, a 128 GiB disk reserve, a 64 GiB per-file ceiling and a 1,800 s execution timeout. Preparation and output auditing have separate 320 GiB/four-core limits and 7,200/1,800 s timeouts. The hosts are shared resources; the study reports one observation per size without inferred uncertainty intervals.

Each layout first passes a separate small-model gate, using 24,000 neurons and 24 million edges per three-host block and the same population/ownership structure. Complete output is compared with the independent single-process Rust reference, requiring exact spikes and event totals and state/trace differences no larger than 1e-12. Large-run acceptance requires complete output reading, finite state/trace values, refractory and spike-count consistency, neuron/edge/event totals, populated rank and host identities, distinct allowed physical-core coverage, exclusive target-owner construction, successful terminal resource records and cleanup. Percentages use an 86-billion-neuron reference count, rounded from the reported adult human neuron-count estimate [16](#ref16); they describe count normalization only. Source identities and complete records are provided in Supplements S19 and S20; historical fixed-host capacity cohorts remain separate in S19.'''
    methods=methods.replace('a fresh availability check with a 64 GiB host-memory reserve',
                            'a fresh availability check with '+reserve_text)
    if final_reserve==48:
        methods=methods.replace('The hosts are shared resources;',
                                'The final worker-admission guard changes only the positive memory-headroom threshold; preparation and audit guards retain a 64 GiB reserve. The hosts are shared resources;')
    text=replace_section(text,'### 4.8 Connected synthetic capacity protocol','## 5. Results',methods)
    results=f'''### 5.10 Large connected synthetic networks and weak scaling

The five configurations completed 100 ms of model time, reaching 860 million neurons and 860 billion connections on 30 hosts and 240 physical worker cores. Counts correspond to 0.1%, 0.2%, 0.4%, 0.8% and 1% of the 86-billion reference, using the same engine snapshot and the protocol in Section 4.8. All layouts passed their small-model numerical gates and complete large-output audits, with successful resource exits and cleanup. These are count-normalized synthetic recurrent E/I networks, not anatomical or functional fractions of a human brain.

**Table 6 | Accepted synthetic weak-scaling observations.** All cases use reference-f64, dt = 0.1 ms, 100 ms model time and exactly 1,000N connections. Eight physical worker cores are used per host. Preparation includes export, code generation, compilation and input hashing. Launch-to-exit excludes preparation, deployment and the independent post-run audit. Stage maxima need not occur on the same rank. Each configuration has one timing observation.

| Reference count | Hosts / ranks | Neurons (M) | Preparation (s) | Launch (s) | Simulation max (s) | Host peak max (GiB) |
|---|---:|---:|---:|---:|---:|---:|'''
    for r in rows:
        results+=f"\n| {r['neuron_count_percent']:g}% | {r['hosts']} / {r['ranks']} | {r['neurons']//1_000_000} | {r['prepare_wall_seconds']:.3f} | {r['launch_wall_seconds']:.3f} | {r['simulation_max_seconds']:.3f} | {r['maximum_worker_cgroup_peak_gib']:.3f} |"
    sim_eff=first['simulation_max_seconds']/last['simulation_max_seconds']
    launch_eff=first['launch_wall_seconds']/last['launch_wall_seconds']
    results+=f'''

From three to 30 hosts, maximum local simulation time changed from {first['simulation_max_seconds']:.3f} to {last['simulation_max_seconds']:.3f} s and launch-to-exit from {first['launch_wall_seconds']:.3f} to {last['launch_wall_seconds']:.3f} s. Their descriptive weak efficiencies, baseline time divided by measured time, are {sim_eff:.3f} and {launch_eff:.3f}, respectively. Centralized preparation also increased from {first['prepare_wall_seconds']:.3f} to {last['prepare_wall_seconds']:.3f} s and is excluded from both efficiencies. Initialization, communication and collection remain separately recorded. Single observations on shared hosts do not establish a precise scaling law; strong scaling with an immutable model and repeated timings is a separate qualification.

The endpoint retained {last['spikes']:,} spikes, counted {last['delivered_synaptic_events']:,} delivered synaptic events and produced {last['output_bytes']:,} output bytes. Maximum coordinator-host and other-host worker cgroup peaks were {last['worker_cgroup_peak_gib'][0]:.3f} and {max(last['worker_cgroup_peak_gib'][1:]):.3f} GiB, respectively, under the 768 GiB coordinator and 655/660 GiB worker limits. Cgroup peaks include charged cache. Host peaks occur at different times and must not be summed as a simultaneous cluster peak. The per-layout numerical gates passed 243, 483, 963, 1,923 and 2,403 checks with exact spikes/events and zero checked state/trace difference; these are small-model comparisons rather than independent reference executions of the large graphs.

Useful local neuron and incoming-edge work remains approximately constant, but global-sized source CSR offsets and spike-receive buffers increase per-rank memory with network size. Ordered spike exchange and result collection also retain global dependencies. The measured capacity therefore does not imply constant memory, constant wall time, or full 86-billion-neuron feasibility through machine addition alone. Earlier 86M/128M/256M fixed-host capacity observations and the smaller 8.6M one-second run use different partitions or snapshots and remain separate in Supplement S19.

![Figure 10. Accepted connected synthetic weak-scaling study.](figures/fig10_connected_capacity.svg)

**Figure 10 | Connected synthetic weak scaling with complete-output acceptance.** (a) Excitatory and inhibitory population rates in the 860-million-neuron run, displayed in 5 ms bins. (b) Maximum local initialization/simulation intervals and measured launch-to-exit across the five layouts. Stage maxima may occur on different ranks and must not be summed. (c) Coordinator-host and maximum other-host worker cgroup peaks, including charged cache, with their respective limits. (d) Descriptive weak efficiency relative to three hosts, shown separately for simulation and launch. The workload family has eight physical worker cores per host, 1,000 expected incoming edges per neuron and 100 ms model time. One observation per size is shown, without inferred uncertainty or a fitted scaling law. Graph realizations change with size.'''
    text=replace_section(text,'### 5.10 Large connected synthetic networks','## 6. Related work and discussion',results)
    text=text.replace('The synthetic 86-million and 128-million capacity observations each cover 100 ms and one run, using an isolated snapshot with explicitly extended neuron limits.', 'The synthetic weak-scaling observations through 860 million neurons each cover 100 ms and one run, using an isolated snapshot with explicitly extended neuron limits.')
    text=text.replace('Feasibility at that scale remains unvalidated: source CSR offsets, frontend count and initial-value limits, IR/output sizes, index bounds, communication and recording all require further evaluation.', 'Feasibility at that scale remains unvalidated: this execution path sizes a spike-receive buffer by the global neuron count and converts its capacity to a signed 32-bit MPI count, while source CSR offsets also depend on global network size. Frontend count and initial-value limits, IR/output sizes, communication and recording require further evaluation.')
    text=text.replace('and reaches 128 million neurons with 128 billion connections in a separate synthetic workload on 30 hosts.', 'and reaches 860 million neurons with 860 billion connections in a five-point synthetic weak-scaling study on up to 30 hosts and 240 physical worker cores.')
    text=text.replace('The [connected-capacity evidence](data/capacity/evidence.json) retains accepted launch/resource reports, complete-output audits and source identities for the isolated 86-million and 128-million configurations.', 'The [connected-capacity evidence](data/capacity/evidence.json) retains historical fixed-host observations, and the [weak-scaling evidence](data/capacity/weak-evidence.json) retains all five accepted layouts through 860 million neurons, their numerical pilots, terminal resource reports, complete-output audits and source identities.')
    text=text.replace('**Table 6 | Feature compatibility','**Table 7 | Feature compatibility')
    assert len(re.findall(r'^\*\*Table \d+ \|',text,re.M))==7
    supplement=ROOT/'SUPPLEMENTARY.md';sup=supplement.read_text()
    assert '## S20.' not in sup
    sup=sup.replace('Appendix A, Table 6 supplies', 'Appendix A, Table 7 supplies')
    sup=sup.replace('Section 4.8 specifies the equations, seeds, weight/delay distributions and recording policy.', 'The historical cohorts use the same LIF equations, initialization, weight/delay distributions and recording policy specified in Section 4.8, but have 30 populations (24 excitatory and six inhibitory), one complete population per rank, and projection seeds 2026100700 + source×30 + target. They are distinct from the five-point weak-scaling layouts.')
    sup=sup.replace("it is not inserted into Figure 10's fixed-host configurations", "it is excluded from Figure 10's controlled weak-scaling curve")
    historical=json.loads((ROOT/'data/capacity/historical-256m-evidence.json').read_text())['row']
    sup+='\n\nA separate [256M fixed-host observation](data/capacity/historical-256m-evidence.json) completed 256 million neurons and 256 billion connections for 100 ms on 30 hosts with two populated ranks and two distinct physical worker cores per host (60 in total). It used 60 populations, 3,600 projections and a separate isolated 256M-ceiling snapshot; default neuron admission remained one million. Launch-to-exit was 879.067 s, maximum local initialization/simulation 453.491/395.447 s, and maximum host worker cgroup peak 180.593 GiB. It retained 323,710,412 spikes, counted 316,251,210,651 delivered events and produced 13,642,135,459 output bytes. The 603-check numerical pilot and complete-output/resource audit passed. This is approximately 0.298% of the reference neuron count; it is excluded from the controlled five-point weak-scaling curve because its process/core allocation, population structure and engine snapshot differ. Its engine/source/fixture and output hashes are retained in the linked evidence.\n'
    sup+='\n## S20. Five-point connected synthetic weak scaling\n\nThe [retained weak-scaling evidence](data/capacity/weak-evidence.json) binds all five accepted observations to their per-layout numerical gates, source identity/readback, deployment audits, terminal resource records and complete-output audits. [collect_scaling_evidence.py](scripts/collect_scaling_evidence.py) copies accepted local records; it starts no remote jobs or simulations and requires the audited 860M endpoint before exporting this study. Full arrays remain in the identified remote experiment directories, bound by model and output-file SHA-256 values.\n\n**Table S3 | Accepted weak-scaling measurements.** Each configuration has one observation, eight distinct physical worker cores per host, reference-f64, dt = 0.1 ms and 100 ms model time. Expected mean indegree is 1,000. Stage maxima may occur on different ranks. Spike exchange is included in simulation; collection is included in launch. Preparation includes input hashing, but launch excludes preparation/deployment and the post-run audit.\n\n'
    sup+='| Measurement | 0.1% | 0.2% | 0.4% | 0.8% | 1% |\n|---|---:|---:|---:|---:|---:|\n'
    measurements=[('Hosts','hosts',lambda v:str(v)),('Ranks / physical worker cores','ranks',lambda v:str(v)),('Neurons (million)','neurons',lambda v:f'{v/1e6:g}'),('Connections (billion)','connections',lambda v:f'{v/1e9:g}'),('Preparation (s)','prepare_wall_seconds',lambda v:f'{v:.3f}'),('Compilation, included in preparation (s)','compile_seconds',lambda v:f'{v:.3f}'),('Launch to exit (s)','launch_wall_seconds',lambda v:f'{v:.3f}'),('Maximum initialization (s)','initialization_max_seconds',lambda v:f'{v:.3f}'),('Maximum simulation (s)','simulation_max_seconds',lambda v:f'{v:.3f}'),('Maximum spike exchange (s)','spike_exchange_max_seconds',lambda v:f'{v:.3f}'),('Maximum collection (s)','collection_max_seconds',lambda v:f'{v:.3f}'),('Maximum host cgroup peak (GiB)','maximum_worker_cgroup_peak_gib',lambda v:f'{v:.3f}'),('Worker cgroup CPU use (core-hours)','worker_cpu_seconds_sum',lambda v:f'{v/3600:.3f}'),('Spikes retained','spikes',lambda v:f'{v:,}'),('Delivered synaptic events','delivered_synaptic_events',lambda v:f'{v:,}'),('Complete output bytes','output_bytes',lambda v:f'{v:,}'),('Independent small-model checks','numerical_pilot_checks',lambda v:str(v))]
    for label,key,format_value in measurements:
        sup+='| '+label+' | '+' | '.join(format_value(r[key]) for r in rows)+' |\n'
    sup+='\nThe engine archive SHA-256 is `'+evidence['source_archive_sha256']+'`. All 156 catalogued source files were read back against their frozen hashes. The unchanged numerical kernels are used with an opt-in 860M neuron ceiling and a one-million default. All per-layout small-model checks passed with exact spikes/events and zero checked state/trace difference. Twenty local resource/layout checks, the isolated Rust budget test and 16 Python resource tests passed before launching the large study. These gates do not independently reproduce the large graphs or establish anatomical/scientific human-brain equivalence.\n'
    if final_reserve==48:
        sup+='\nThe final 30-host worker launch uses a separately identified [admission guard](data/capacity/weak-guard-host-reserve48-v3.py), SHA-256 `'+last['admission_guard_sha256']+'`, retaining a 48 GiB available-memory reserve. Earlier worker layouts, preparation and independent output auditing retain 64 GiB. Eleven guard tests verify positive admission, rejection below the threshold, unprivileged execution and active memory/swap/CPU/task/file limits. The final 2,403-check numerical gate also passed under this guard. The engine, model, B2IR, compiled program, eight-core placement and hard execution caps are unchanged; preparation is measured once from the hash-bound reused inputs.\n'
    sup+='\nEach three-host block owns 19 excitatory and five inhibitory populations, whose different sizes preserve exactly 80%/20% of neurons. Each complete population belongs to one rank. The host pattern is six excitatory/two inhibitory, six/two, and seven/one; it repeats at all scales. Exactly 1,000N connections are allocated across every population pair by deterministic largest-remainder allocation. Each projection permits autapses and multapses. Model and projection seeds, equations, initialization, delay/weight distributions and recording are specified in Section 4.8. Host count changes the global network and graph realization, while preserving useful per-rank population/incoming-edge work approximately.\n'
    sup+='\nMPI uses the retained MPICH 4.2.3 ch3:sock runtime over private networking. Hosts have matching dual-socket EPYC 9454 hardware; nominal 50,000 Mb/s bonds are not measured usable throughput. CPU IDs 1, 13, 25, 37, 49, 61, 73 and 85 were verified as distinct physical cores on every host. Runtime affinity uses topology-aware ordering; acceptance checks each host owns exactly the admitted physical-core set and eight ranks, with required pinning. Nodes are shared rather than exclusive, so before/after load, CPU and availability snapshots are retained and single timings have no inferred error bars.\n'
    sup+='\nLimits were prospective and finite: worker/coordinator memory 665/768 GiB at 3–12 hosts and 655/660 GiB worker limits (by host population layout) with 768 GiB on the coordinator at 24/30 hosts, eight worker cores per host, zero swap, '+reserve_text+' beyond the requested worker memory limit, 128 GiB disk reserve, 64 GiB per-file cap and 1,800 s execution timeout. Preparation/auditing have separate 320 GiB/four-core guards, with 7,200/1,800 s timeouts. The local edge cap is 4.29 billion per rank, below the unsigned-32-bit index bound; maximum useful incoming work is approximately 3.621 billion edges per rank. Initial-value and IR admission limits are four billion values and 64 GiB. All terminal workers/guards exited zero, OOM counters remained zero, and worker-service cleanup passed. Cgroup peaks include charged cache; summing peaks from different hosts does not yield a simultaneous cluster peak.\n'
    sup+='\nDense source CSR offsets and spike-receive buffers depend on global neuron count on each rank, and projection/rank metadata also grows. Spike exchange includes packing, synchronization, sorting, validation and scattering rather than pure network time. The current receive-capacity conversion uses signed 32-bit MPI counts. The observations therefore test a bounded synthetic capacity/scaling range through 1%, not maximum capacity, a proportional anatomical brain model, full-86B feasibility, long-duration behavior at the large sizes, or matched superiority over another simulator. Fixed-model strong scaling and repeated timing remain distinct qualifications.\n'
    supplement.write_text(sup)
    path.write_text(text)
    print(json.dumps({'passed':True,'updated_endpoint_neurons':last['neurons'],'tables':7}))

if __name__=='__main__':main()
